# Generated by Django 3.2.13 on 2022-06-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(max_length=10)),
                ('model', models.CharField(max_length=64, null=True)),
                ('brand', models.CharField(default='unknown', max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1024)),
                ('date', models.DateField(verbose_name='review date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.car')),
            ],
        ),
    ]
